apiVersion: batch/v1
kind: Job
metadata:
  name: {{ job_name }}
  labels:
    jobgroup: reconstruction

spec:
  backoffLimit: 0

  template:
    spec:
      restartPolicy: Never

      containers:
      - name: frames-container
        image: gitlab-registry.nrp-nautilus.io/creallf/plant-segmentation-container-registry:frames
        command: ["sh", "-c", "curl -O https://raw.githubusercontent.com/evieteru/scaling_up/refs/heads/main/job_manager/runtime_scripts/extract.sh && bash -x extract.sh $BUCKET_NAME $JOB_FOLDER_PATH $VIDEO_FILE_NAME $FRAMES_ARCHIVE_FILE_NAME"]
        imagePullPolicy: Always
        resources:
          limits:
            memory: 8G
            cpu: 3
          requests:
            memory: 8G
            cpu: 3

        volumeMounts:
        - mountPath: /secrets
          name: sec

        env:
        - name: BUCKET_NAME
          value: {{ bucket_name }}
        - name: JOB_FOLDER_PATH
          value: {{ job_folder_path }}
        - name: VIDEO_FILE_NAME
          value: {{ video_file_name }}
        - name: FRAMES_ARCHIVE_FILE_NAME
          value: {{ frames_archive_file_name }}

      volumes:
      - name: sec
        secret:
          secretName: rcloneconfig
