apiVersion: batch/v1
kind: Job
metadata:
  name: {{ job_name }}
  labels:
    jobgroup: reconstruction

spec:
  backoffLimit: 0

  template:
    spec:
      restartPolicy: Never

      containers:
      - name: framescontainer
        image: gitlab-registry.nrp-nautilus.io/creallf/plant-segmentation-container-registry:frames
        command: ["sh", "-c", "curl -O https://raw.githubusercontent.com/evieteru/scaling_up/refs/heads/main/job_manager/runtime_scripts/extract.sh && bash -x extract.sh $VIDEO_BUCKET $VIDEO_FILE_PATH"]
        imagePullPolicy: Always
        resources:
          limits:
            memory: 8G
            cpu: 3
          requests:
            memory: 8G
            cpu: 3
        volumeMounts:
        - mountPath: /secrets
          name: sec
        env:
        - name: VIDEO_BUCKET
          value: {{ video_bucket }}
        - name: VIDEO_FILE_PATH
          value: {{ video_file_path }}

      volumes:
      - name: sec
        secret:
          secretName: rcloneconfig
