# this is ../e/pointillist_maize/code/scaling_up/pvc-pod.yaml
#
# Wilbur and Fluharty, 11.2.2025
#
apiVersion: v1
kind: Pod
metadata:
  name: single-video-pod
spec:
  containers:
  - name: single-video
    image: gitlab-registry.nrp-nautilus.io/creallf/plant-segmentation-container-registry:notlatest
    command: ["sh", "-c", "curl -O https://raw.githubusercontent.com/evieteru/scaling_up/refs/heads/main/pointify.sh && bash pointify.sh"]
    resources:
      limits:
        memory: 8G
        cpu: 1
        nvidia.com/gpu: 1
      requests:
        memory: 8G
        cpu: 1
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /pvc
      name: pvc
    - mountPath: /secrets
      name: sec
#
# set owner to ubuntu and change permissions on /pvc
#
  initContainers:
  - name: chmod-permissions
    image: ubuntu:latest
    command: ["chmod", "-R", "777", "/pvc"]
    volumeMounts:
    - mountPath: /pvc
      name: pvc
#
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - mizzou
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: single-video-vol
    - name: sec
      secret:
        secretName: rcloneconfig
