# this is ../e/pointillist_maize/code/scaling_up/reconstruction.yaml
#
# Wilbur and Fluharty, 11.2.2025

apiVersion: batch/v1
kind: Job
metadata:
  name: reconstruction

spec:
  backoffLimit: 0

  template:
    spec:
      restartPolicy: Never

      containers:
      - name: reconstruction
        image: gitlab-registry.nrp-nautilus.io/creallf/plant-segmentation-container-registry:reconstruction
        command: ["sh", "-c", "curl -O https://raw.githubusercontent.com/evieteru/scaling_up/refs/heads/main/reconstruct.sh && bash -x reconstruct.sh"]
        imagePullPolicy: Always
        resources:
          limits:
            memory: 64G
            cpu: 24
            nvidia.com/gpu: 1
          requests:
            memory: 64G
            cpu: 24
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /pvc
          name: pvc
        - mountPath: /secrets
          name: sec

      initContainers:
      - name: chmod-permissions
        image: ubuntu:latest
        command: ["chmod", "-R", "777", "/pvc"]
        resources:
          limits:
            memory: 100Mi
            cpu: 1
          requests:
            memory: 100Mi
            cpu: 1
        volumeMounts:
        - mountPath: /pvc
          name: pvc

      nodeSelector:
        nvidia.com/cuda.runtime-version.full: "12.8"

      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: topology.kubernetes.io/zone
      #           operator: In
      #           values:
      #           - mizzou

      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: single-video-vol
        - name: sec
          secret:
            secretName: rcloneconfig
