apiVersion: v1
kind: Pod
metadata:
  name: vggt-test

spec:
  containers:
    - name: vggt-test-container
      image: gitlab-registry.nrp-nautilus.io/creallf/plant-segmentation-container-registry:vggt
      command: ["sh", "-c", "curl -O https://raw.githubusercontent.com/evieteru/scaling_up/refs/heads/main/vggt/vggt_reconstruct.sh && bash -x vggt_reconstruct.sh"]
      imagePullPolicy: Always

      resources:
        limits:
          memory: 8G
          cpu: 3
          nvidia.com/gpu: 1
        requests:
          memory: 8G
          cpu: 3
          nvidia.com/gpu: 1

      volumeMounts:
        - mountPath: /secrets
          name: secrets

  volumes:
    - name: secrets
      secret:
        secretName: rcloneconfig